### ISSUE TITLE
Music not playing

### ISSUE THREAD

**Issue by Tehniels2000** [Hazmi35/jukebox#1069]
When the command is issued to request a song, the following error shows up in the docker log. The song also does not start playing in discord.

err: {

      "type": "TypeError",

      "message": "Cannot read properties of undefined (reading 'response')",

      "stack":

          TypeError: Cannot read properties of undefined (reading 'response')

              at Client.<anonymous> (/app/node_modules/youtubei/dist/classes/Client.js:76:35)

              at Generator.next (<anonymous>)

              at fulfilled (/app/node_modules/youtubei/dist/classes/Client.js:5:58)

              at processTicksAndRejections (node:internal/process/task_queues:96:5)

    }

[2022-04-07 20:00:57.184 +0000] ERROR (Shard #0): Unknown Message

    err: {

      "type": "DiscordAPIError",

      "message": "Unknown Message",

      "stack":

          DiscordAPIError: Unknown Message

              at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)

              at processTicksAndRejections (node:internal/process/task_queues:96:5)

              at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)

              at async MessageManager.delete (/app/node_modules/discord.js/src/managers/MessageManager.js:210:5)

              at async Message.delete (/app/node_modules/discord.js/src/structures/Message.js:792:5)

      "name": "DiscordAPIError",

      "method": "delete",

      "path": "/channels/888166126142500874/messages/961717229995581470",

      "code": 10008,

      "httpStatus": 404,

      "requestData": {

        "files": []

      }

**Comment by Hazmi35** [comment]
Duplicate, please see #1066
