### ISSUE TITLE
incorrect header check when I add youtube playlist

### ISSUE THREAD

**Issue by FloxY-Y** [Hazmi35/jukebox#825]
Hello,
when i add a youtube playlist the bot tries to retrieve all the videos of the playlist but can't and leaves me with an error : incorrect header check

here are the error logs returned in the console:
```
[11/4/21, 14:55:27] [error]: Error: Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)
    at PlayCommand.loadRestVideosFromPlaylist (/XXX/jukebox/dist/commands/PlayCommand.js:256:60)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PlayCommand.loadPlaylist (/XXX/jukebox/dist/commands/PlayCommand.js:199:24)
```

**Comment by Hazmi35** [comment]
Does this happen with every playlist? if not then can you send here the URL for that specific playlist?

**Comment by FloxY-Y** [comment]
> Does this happen with every playlist? if not then can you send here the URL for that specific playlist?
Yes this happen with every playlist

**Comment by Hazmi35** [comment]
Couldn't reproduce, what version of Jukebox do you use? and what Node.js version?

**Comment by FloxY-Y** [comment]
I use the vertion of the last commit in the main branch
and I use NodeJS 16.11.1-1

**Comment by Hazmi35** [comment]
I still can't reproduce it even in a similar environment. Are you sure it happens with every playlist? Can you try reinstalling nodejs or try using nodejs-lts-gallium?

**Comment by FloxY-Y** [comment]
I have retested with other playlists and I have the impression that it is linked to my playlist.
and it also means that I have had one of those bad luck for the second playlist that I test to see if it's related to mine makes the same mistake

playlists :
https://www.youtube.com/playlist?list=PLTDZuBz4pe1ruKvbGlbmZPcMU7LsspIhx

ah and also the other playlist I tested has another error : 
```
[11/13/21, 13:40:55] [error]: Error: TypeError: Cannot read properties of undefined (reading 'secondaryResults')
    at Video.load (/XXX/jukebox/node_modules/youtubei/dist/classes/BaseVideo.js:58:104)
    at Video.load (/XXX/jukebox/node_modules/youtubei/dist/classes/Video.js:34:15)
    at Client.<anonymous> (/XXX/jukebox/node_modules/youtubei/dist/classes/Client.js:79:50)
    at Generator.next (<anonymous>)
    at fulfilled (/XXX/jukebox/node_modules/youtubei/dist/classes/Client.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PlayCommand.loadRestVideosFromPlaylist (/XXX/jukebox/dist/commands/PlayCommand.js:256:60)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PlayCommand.loadPlaylist (/XXX/jukebox/dist/commands/PlayCommand.js:199:24)
```
playlist : 
https://www.youtube.com/playlist?list=PL6bqikrDRqu2cShwgEgAjqSX1X_SiueN9

**Comment by Hazmi35** [comment]
I still can't reproduce it, I'm also on Arch WSL, also on the same Node.js version, well it's on Windows 11 but there won't be a difference.

Anyway, with #844 merged, can you try again?

**Comment by FloxY-Y** [comment]
everything works thank you ^^
